// Code generated by "daox"; DO NOT EDIT.
package sysdict

import (
	"github.com/fengjx/daox/v2/sqlbuilder"
	"github.com/fengjx/daox/v2/sqlbuilder/ql"

	"time"
)

const (
	TableName      = "sys_dict"
	IDField        = "id"
	GroupField     = "group"
	GroupNameField = "group_name"
	ValueField     = "value"
	LabelField     = "label"
	StatusField    = "status"
	RemarkField    = "remark"
	UtimeField     = "utime"
	CtimeField     = "ctime"
)

var Meta = SysdictMeta{}

// SysDictM 系统字典表
type SysdictMeta struct {
}

func (m SysdictMeta) TableName() string {
	return TableName
}

func (m SysdictMeta) IsAutoIncrement() bool {
	return true
}

func (m SysdictMeta) PrimaryKey() string {
	return "id"
}

func (m SysdictMeta) Columns() []string {
	return []string{
		"id",
		"group",
		"group_name",
		"value",
		"label",
		"status",
		"remark",
		"utime",
		"ctime",
	}
}

func IdIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).In(args...)
}

func IdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).NotIn(args...)
}

func IdEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).EQ(val)
}

func IdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).NotEQ(val)
}

func IdLT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LT(val)
}

func IdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LTEQ(val)
}

func IdGT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GT(val)
}

func IdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GTEQ(val)
}

func IdLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).Like(val)
}

func IdNotLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).NotLike(val)
}

func IdDesc() sqlbuilder.OrderBy {
	return ql.Desc(IDField)
}

func IdAsc() sqlbuilder.OrderBy {
	return ql.Asc(IDField)
}

func GroupIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(GroupField).In(args...)
}

func GroupNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(GroupField).NotIn(args...)
}

func GroupEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupField).EQ(val)
}

func GroupNotEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupField).NotEQ(val)
}

func GroupLT(val string) sqlbuilder.Column {
	return ql.Col(GroupField).LT(val)
}

func GroupLTEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupField).LTEQ(val)
}

func GroupGT(val string) sqlbuilder.Column {
	return ql.Col(GroupField).GT(val)
}

func GroupGTEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupField).GTEQ(val)
}

func GroupLike(val string) sqlbuilder.Column {
	return ql.Col(GroupField).Like(val)
}

func GroupNotLike(val string) sqlbuilder.Column {
	return ql.Col(GroupField).NotLike(val)
}

func GroupDesc() sqlbuilder.OrderBy {
	return ql.Desc(GroupField)
}

func GroupAsc() sqlbuilder.OrderBy {
	return ql.Asc(GroupField)
}

func GroupNameIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(GroupNameField).In(args...)
}

func GroupNameNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(GroupNameField).NotIn(args...)
}

func GroupNameEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).EQ(val)
}

func GroupNameNotEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).NotEQ(val)
}

func GroupNameLT(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).LT(val)
}

func GroupNameLTEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).LTEQ(val)
}

func GroupNameGT(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).GT(val)
}

func GroupNameGTEQ(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).GTEQ(val)
}

func GroupNameLike(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).Like(val)
}

func GroupNameNotLike(val string) sqlbuilder.Column {
	return ql.Col(GroupNameField).NotLike(val)
}

func GroupNameDesc() sqlbuilder.OrderBy {
	return ql.Desc(GroupNameField)
}

func GroupNameAsc() sqlbuilder.OrderBy {
	return ql.Asc(GroupNameField)
}

func ValueIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ValueField).In(args...)
}

func ValueNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ValueField).NotIn(args...)
}

func ValueEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).EQ(val)
}

func ValueNotEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).NotEQ(val)
}

func ValueLT(val string) sqlbuilder.Column {
	return ql.Col(ValueField).LT(val)
}

func ValueLTEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).LTEQ(val)
}

func ValueGT(val string) sqlbuilder.Column {
	return ql.Col(ValueField).GT(val)
}

func ValueGTEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).GTEQ(val)
}

func ValueLike(val string) sqlbuilder.Column {
	return ql.Col(ValueField).Like(val)
}

func ValueNotLike(val string) sqlbuilder.Column {
	return ql.Col(ValueField).NotLike(val)
}

func ValueDesc() sqlbuilder.OrderBy {
	return ql.Desc(ValueField)
}

func ValueAsc() sqlbuilder.OrderBy {
	return ql.Asc(ValueField)
}

func LabelIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(LabelField).In(args...)
}

func LabelNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(LabelField).NotIn(args...)
}

func LabelEQ(val string) sqlbuilder.Column {
	return ql.Col(LabelField).EQ(val)
}

func LabelNotEQ(val string) sqlbuilder.Column {
	return ql.Col(LabelField).NotEQ(val)
}

func LabelLT(val string) sqlbuilder.Column {
	return ql.Col(LabelField).LT(val)
}

func LabelLTEQ(val string) sqlbuilder.Column {
	return ql.Col(LabelField).LTEQ(val)
}

func LabelGT(val string) sqlbuilder.Column {
	return ql.Col(LabelField).GT(val)
}

func LabelGTEQ(val string) sqlbuilder.Column {
	return ql.Col(LabelField).GTEQ(val)
}

func LabelLike(val string) sqlbuilder.Column {
	return ql.Col(LabelField).Like(val)
}

func LabelNotLike(val string) sqlbuilder.Column {
	return ql.Col(LabelField).NotLike(val)
}

func LabelDesc() sqlbuilder.OrderBy {
	return ql.Desc(LabelField)
}

func LabelAsc() sqlbuilder.OrderBy {
	return ql.Asc(LabelField)
}

func StatusIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).In(args...)
}

func StatusNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).NotIn(args...)
}

func StatusEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).EQ(val)
}

func StatusNotEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotEQ(val)
}

func StatusLT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LT(val)
}

func StatusLTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LTEQ(val)
}

func StatusGT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GT(val)
}

func StatusGTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GTEQ(val)
}

func StatusLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).Like(val)
}

func StatusNotLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotLike(val)
}

func StatusDesc() sqlbuilder.OrderBy {
	return ql.Desc(StatusField)
}

func StatusAsc() sqlbuilder.OrderBy {
	return ql.Asc(StatusField)
}

func RemarkIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).In(args...)
}

func RemarkNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).NotIn(args...)
}

func RemarkEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).EQ(val)
}

func RemarkNotEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotEQ(val)
}

func RemarkLT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LT(val)
}

func RemarkLTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LTEQ(val)
}

func RemarkGT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GT(val)
}

func RemarkGTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GTEQ(val)
}

func RemarkLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).Like(val)
}

func RemarkNotLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotLike(val)
}

func RemarkDesc() sqlbuilder.OrderBy {
	return ql.Desc(RemarkField)
}

func RemarkAsc() sqlbuilder.OrderBy {
	return ql.Asc(RemarkField)
}

func UtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).In(args...)
}

func UtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).NotIn(args...)
}

func UtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).EQ(val)
}

func UtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).NotEQ(val)
}

func UtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LT(val)
}

func UtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LTEQ(val)
}

func UtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GT(val)
}

func UtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GTEQ(val)
}

func UtimeLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).Like(val)
}

func UtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).NotLike(val)
}

func UtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(UtimeField)
}

func UtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(UtimeField)
}

func CtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).In(args...)
}

func CtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).NotIn(args...)
}

func CtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).EQ(val)
}

func CtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).NotEQ(val)
}

func CtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LT(val)
}

func CtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LTEQ(val)
}

func CtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GT(val)
}

func CtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GTEQ(val)
}

func CtimeLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).Like(val)
}

func CtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).NotLike(val)
}

func CtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(CtimeField)
}

func CtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(CtimeField)
}
