ds:
  type: mysql
  dsn: root:123456@tcp(192.168.6.121:3306)/lucky?charset=utf8mb4
target:
  custom:
    tag-name: json
    gomod: github.com/fengjx/lucky
  tables:
    sys_user:
      simple-name: user
      target-dir: logic/sys/internal/dao
    sys_config:
      simple-name: config
      target-dir: logic/sys/internal/dao
    sys_dict:
      simple-name: dict
      target-dir: logic/sys/internal/dao
    cms_news:
      simple-name: news
      target-dir: logic/cms/internal/dao
