// Code generated by "daox"; DO NOT EDIT.
package sysconfig

import (
	"github.com/fengjx/daox/v2/sqlbuilder"
	"github.com/fengjx/daox/v2/sqlbuilder/ql"

	"time"
)

const (
	TableName   = "sys_config"
	IDField     = "id"
	ScopeField  = "scope"
	KeyField    = "key"
	ValueField  = "value"
	StatusField = "status"
	RemarkField = "remark"
	UtimeField  = "utime"
	CtimeField  = "ctime"
)

var Meta = SysconfigMeta{}

// SysConfigM 系统配置
type SysconfigMeta struct {
}

func (m SysconfigMeta) TableName() string {
	return TableName
}

func (m SysconfigMeta) IsAutoIncrement() bool {
	return true
}

func (m SysconfigMeta) PrimaryKey() string {
	return "id"
}

func (m SysconfigMeta) Columns() []string {
	return []string{
		"id",
		"scope",
		"key",
		"value",
		"status",
		"remark",
		"utime",
		"ctime",
	}
}

func IdIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).In(args...)
}

func IdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).NotIn(args...)
}

func IdEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).EQ(val)
}

func IdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).NotEQ(val)
}

func IdLT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LT(val)
}

func IdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LTEQ(val)
}

func IdGT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GT(val)
}

func IdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GTEQ(val)
}

func IdLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).Like(val)
}

func IdNotLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).NotLike(val)
}

func IdDesc() sqlbuilder.OrderBy {
	return ql.Desc(IDField)
}

func IdAsc() sqlbuilder.OrderBy {
	return ql.Asc(IDField)
}

func ScopeIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ScopeField).In(args...)
}

func ScopeNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ScopeField).NotIn(args...)
}

func ScopeEQ(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).EQ(val)
}

func ScopeNotEQ(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).NotEQ(val)
}

func ScopeLT(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).LT(val)
}

func ScopeLTEQ(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).LTEQ(val)
}

func ScopeGT(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).GT(val)
}

func ScopeGTEQ(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).GTEQ(val)
}

func ScopeLike(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).Like(val)
}

func ScopeNotLike(val string) sqlbuilder.Column {
	return ql.Col(ScopeField).NotLike(val)
}

func ScopeDesc() sqlbuilder.OrderBy {
	return ql.Desc(ScopeField)
}

func ScopeAsc() sqlbuilder.OrderBy {
	return ql.Asc(ScopeField)
}

func KeyIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(KeyField).In(args...)
}

func KeyNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(KeyField).NotIn(args...)
}

func KeyEQ(val string) sqlbuilder.Column {
	return ql.Col(KeyField).EQ(val)
}

func KeyNotEQ(val string) sqlbuilder.Column {
	return ql.Col(KeyField).NotEQ(val)
}

func KeyLT(val string) sqlbuilder.Column {
	return ql.Col(KeyField).LT(val)
}

func KeyLTEQ(val string) sqlbuilder.Column {
	return ql.Col(KeyField).LTEQ(val)
}

func KeyGT(val string) sqlbuilder.Column {
	return ql.Col(KeyField).GT(val)
}

func KeyGTEQ(val string) sqlbuilder.Column {
	return ql.Col(KeyField).GTEQ(val)
}

func KeyLike(val string) sqlbuilder.Column {
	return ql.Col(KeyField).Like(val)
}

func KeyNotLike(val string) sqlbuilder.Column {
	return ql.Col(KeyField).NotLike(val)
}

func KeyDesc() sqlbuilder.OrderBy {
	return ql.Desc(KeyField)
}

func KeyAsc() sqlbuilder.OrderBy {
	return ql.Asc(KeyField)
}

func ValueIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ValueField).In(args...)
}

func ValueNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ValueField).NotIn(args...)
}

func ValueEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).EQ(val)
}

func ValueNotEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).NotEQ(val)
}

func ValueLT(val string) sqlbuilder.Column {
	return ql.Col(ValueField).LT(val)
}

func ValueLTEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).LTEQ(val)
}

func ValueGT(val string) sqlbuilder.Column {
	return ql.Col(ValueField).GT(val)
}

func ValueGTEQ(val string) sqlbuilder.Column {
	return ql.Col(ValueField).GTEQ(val)
}

func ValueLike(val string) sqlbuilder.Column {
	return ql.Col(ValueField).Like(val)
}

func ValueNotLike(val string) sqlbuilder.Column {
	return ql.Col(ValueField).NotLike(val)
}

func ValueDesc() sqlbuilder.OrderBy {
	return ql.Desc(ValueField)
}

func ValueAsc() sqlbuilder.OrderBy {
	return ql.Asc(ValueField)
}

func StatusIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).In(args...)
}

func StatusNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).NotIn(args...)
}

func StatusEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).EQ(val)
}

func StatusNotEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotEQ(val)
}

func StatusLT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LT(val)
}

func StatusLTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LTEQ(val)
}

func StatusGT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GT(val)
}

func StatusGTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GTEQ(val)
}

func StatusLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).Like(val)
}

func StatusNotLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotLike(val)
}

func StatusDesc() sqlbuilder.OrderBy {
	return ql.Desc(StatusField)
}

func StatusAsc() sqlbuilder.OrderBy {
	return ql.Asc(StatusField)
}

func RemarkIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).In(args...)
}

func RemarkNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).NotIn(args...)
}

func RemarkEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).EQ(val)
}

func RemarkNotEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotEQ(val)
}

func RemarkLT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LT(val)
}

func RemarkLTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LTEQ(val)
}

func RemarkGT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GT(val)
}

func RemarkGTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GTEQ(val)
}

func RemarkLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).Like(val)
}

func RemarkNotLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotLike(val)
}

func RemarkDesc() sqlbuilder.OrderBy {
	return ql.Desc(RemarkField)
}

func RemarkAsc() sqlbuilder.OrderBy {
	return ql.Asc(RemarkField)
}

func UtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).In(args...)
}

func UtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).NotIn(args...)
}

func UtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).EQ(val)
}

func UtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).NotEQ(val)
}

func UtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LT(val)
}

func UtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LTEQ(val)
}

func UtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GT(val)
}

func UtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GTEQ(val)
}

func UtimeLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).Like(val)
}

func UtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).NotLike(val)
}

func UtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(UtimeField)
}

func UtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(UtimeField)
}

func CtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).In(args...)
}

func CtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).NotIn(args...)
}

func CtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).EQ(val)
}

func CtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).NotEQ(val)
}

func CtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LT(val)
}

func CtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LTEQ(val)
}

func CtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GT(val)
}

func CtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GTEQ(val)
}

func CtimeLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).Like(val)
}

func CtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).NotLike(val)
}

func CtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(CtimeField)
}

func CtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(CtimeField)
}
