// Code generated by "daox.gen"; DO NOT EDIT.
package entity


import (
	"time"
)


// CmsNews 新闻信息表
type CmsNews struct {
    ID int64 `json:"id"` // -
    Title string `json:"title"` // 标题
    Content string `json:"content"` // 内容
    Topic string `json:"topic"` // 主题
    Status string `json:"status"` // 状态
    Remark string `json:"remark"` // 备注
    Utime time.Time `json:"utime"` // 更新时间
    Ctime time.Time `json:"ctime"` // 创建时间
}

func (m *CmsNews) GetID() interface{} {
	return m.ID
}