// Code generated by "daox.gen"; DO NOT EDIT.
package meta

import (
    "github.com/fengjx/daox/sqlbuilder"
    "github.com/fengjx/daox/sqlbuilder/ql"


    "time"

)



// CmsUserM cms用户信息表
type CmsUserM struct {
    ID string
    Username string
    Pwd string
    Salt string
    Email string
    Nickname string
    Avatar string
    Status string
    Remark string
    Utime string
    Ctime string
}

func (m CmsUserM) TableName() string {
    return "cms_user"
}

func (m CmsUserM) IsAutoIncrement() bool {
    return true
}

func (m CmsUserM) PrimaryKey() string {
    return "id"
}

func (m CmsUserM) Columns() []string {
	return []string{
        "id",
        "username",
        "pwd",
        "salt",
        "email",
        "nickname",
        "avatar",
        "status",
        "remark",
        "utime",
        "ctime",
    }
}

var CmsUserMeta = CmsUserM{
    ID: "id",
    Username: "username",
    Pwd: "pwd",
    Salt: "salt",
    Email: "email",
    Nickname: "nickname",
    Avatar: "avatar",
    Status: "status",
    Remark: "remark",
    Utime: "utime",
    Ctime: "ctime",
}




func (m CmsUserM) IdIn(vals ...int64) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.ID).In(args...)
}

func (m CmsUserM) IdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.ID).NotIn(args...)
}

func (m CmsUserM) IdEQ(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).EQ(val)
}

func (m CmsUserM) IdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).NotEQ(val)
}

func (m CmsUserM) IdLT(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).LT(val)
}

func (m CmsUserM) IdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).LTEQ(val)
}

func (m CmsUserM) IdGT(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).GT(val)
}

func (m CmsUserM) IdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).GTEQ(val)
}

func (m CmsUserM) IdLike(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).Like(val)
}

func (m CmsUserM) IdNotLike(val int64) sqlbuilder.Column {
	return ql.Col(m.ID).NotLike(val)
}

func (m CmsUserM) IdDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.ID)
}

func (m CmsUserM) IdAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.ID)
}



func (m CmsUserM) UsernameIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Username).In(args...)
}

func (m CmsUserM) UsernameNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Username).NotIn(args...)
}

func (m CmsUserM) UsernameEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Username).EQ(val)
}

func (m CmsUserM) UsernameNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Username).NotEQ(val)
}

func (m CmsUserM) UsernameLT(val string) sqlbuilder.Column {
	return ql.Col(m.Username).LT(val)
}

func (m CmsUserM) UsernameLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Username).LTEQ(val)
}

func (m CmsUserM) UsernameGT(val string) sqlbuilder.Column {
	return ql.Col(m.Username).GT(val)
}

func (m CmsUserM) UsernameGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Username).GTEQ(val)
}

func (m CmsUserM) UsernameLike(val string) sqlbuilder.Column {
	return ql.Col(m.Username).Like(val)
}

func (m CmsUserM) UsernameNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Username).NotLike(val)
}

func (m CmsUserM) UsernameDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Username)
}

func (m CmsUserM) UsernameAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Username)
}



func (m CmsUserM) PwdIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Pwd).In(args...)
}

func (m CmsUserM) PwdNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Pwd).NotIn(args...)
}

func (m CmsUserM) PwdEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).EQ(val)
}

func (m CmsUserM) PwdNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).NotEQ(val)
}

func (m CmsUserM) PwdLT(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).LT(val)
}

func (m CmsUserM) PwdLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).LTEQ(val)
}

func (m CmsUserM) PwdGT(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).GT(val)
}

func (m CmsUserM) PwdGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).GTEQ(val)
}

func (m CmsUserM) PwdLike(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).Like(val)
}

func (m CmsUserM) PwdNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Pwd).NotLike(val)
}

func (m CmsUserM) PwdDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Pwd)
}

func (m CmsUserM) PwdAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Pwd)
}



func (m CmsUserM) SaltIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Salt).In(args...)
}

func (m CmsUserM) SaltNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Salt).NotIn(args...)
}

func (m CmsUserM) SaltEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).EQ(val)
}

func (m CmsUserM) SaltNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).NotEQ(val)
}

func (m CmsUserM) SaltLT(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).LT(val)
}

func (m CmsUserM) SaltLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).LTEQ(val)
}

func (m CmsUserM) SaltGT(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).GT(val)
}

func (m CmsUserM) SaltGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).GTEQ(val)
}

func (m CmsUserM) SaltLike(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).Like(val)
}

func (m CmsUserM) SaltNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Salt).NotLike(val)
}

func (m CmsUserM) SaltDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Salt)
}

func (m CmsUserM) SaltAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Salt)
}



func (m CmsUserM) EmailIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Email).In(args...)
}

func (m CmsUserM) EmailNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Email).NotIn(args...)
}

func (m CmsUserM) EmailEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Email).EQ(val)
}

func (m CmsUserM) EmailNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Email).NotEQ(val)
}

func (m CmsUserM) EmailLT(val string) sqlbuilder.Column {
	return ql.Col(m.Email).LT(val)
}

func (m CmsUserM) EmailLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Email).LTEQ(val)
}

func (m CmsUserM) EmailGT(val string) sqlbuilder.Column {
	return ql.Col(m.Email).GT(val)
}

func (m CmsUserM) EmailGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Email).GTEQ(val)
}

func (m CmsUserM) EmailLike(val string) sqlbuilder.Column {
	return ql.Col(m.Email).Like(val)
}

func (m CmsUserM) EmailNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Email).NotLike(val)
}

func (m CmsUserM) EmailDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Email)
}

func (m CmsUserM) EmailAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Email)
}



func (m CmsUserM) NicknameIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Nickname).In(args...)
}

func (m CmsUserM) NicknameNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Nickname).NotIn(args...)
}

func (m CmsUserM) NicknameEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).EQ(val)
}

func (m CmsUserM) NicknameNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).NotEQ(val)
}

func (m CmsUserM) NicknameLT(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).LT(val)
}

func (m CmsUserM) NicknameLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).LTEQ(val)
}

func (m CmsUserM) NicknameGT(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).GT(val)
}

func (m CmsUserM) NicknameGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).GTEQ(val)
}

func (m CmsUserM) NicknameLike(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).Like(val)
}

func (m CmsUserM) NicknameNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Nickname).NotLike(val)
}

func (m CmsUserM) NicknameDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Nickname)
}

func (m CmsUserM) NicknameAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Nickname)
}



func (m CmsUserM) AvatarIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Avatar).In(args...)
}

func (m CmsUserM) AvatarNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Avatar).NotIn(args...)
}

func (m CmsUserM) AvatarEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).EQ(val)
}

func (m CmsUserM) AvatarNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).NotEQ(val)
}

func (m CmsUserM) AvatarLT(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).LT(val)
}

func (m CmsUserM) AvatarLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).LTEQ(val)
}

func (m CmsUserM) AvatarGT(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).GT(val)
}

func (m CmsUserM) AvatarGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).GTEQ(val)
}

func (m CmsUserM) AvatarLike(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).Like(val)
}

func (m CmsUserM) AvatarNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Avatar).NotLike(val)
}

func (m CmsUserM) AvatarDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Avatar)
}

func (m CmsUserM) AvatarAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Avatar)
}



func (m CmsUserM) StatusIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Status).In(args...)
}

func (m CmsUserM) StatusNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Status).NotIn(args...)
}

func (m CmsUserM) StatusEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Status).EQ(val)
}

func (m CmsUserM) StatusNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Status).NotEQ(val)
}

func (m CmsUserM) StatusLT(val string) sqlbuilder.Column {
	return ql.Col(m.Status).LT(val)
}

func (m CmsUserM) StatusLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Status).LTEQ(val)
}

func (m CmsUserM) StatusGT(val string) sqlbuilder.Column {
	return ql.Col(m.Status).GT(val)
}

func (m CmsUserM) StatusGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Status).GTEQ(val)
}

func (m CmsUserM) StatusLike(val string) sqlbuilder.Column {
	return ql.Col(m.Status).Like(val)
}

func (m CmsUserM) StatusNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Status).NotLike(val)
}

func (m CmsUserM) StatusDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Status)
}

func (m CmsUserM) StatusAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Status)
}



func (m CmsUserM) RemarkIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Remark).In(args...)
}

func (m CmsUserM) RemarkNotIn(vals ...string) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Remark).NotIn(args...)
}

func (m CmsUserM) RemarkEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).EQ(val)
}

func (m CmsUserM) RemarkNotEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).NotEQ(val)
}

func (m CmsUserM) RemarkLT(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).LT(val)
}

func (m CmsUserM) RemarkLTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).LTEQ(val)
}

func (m CmsUserM) RemarkGT(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).GT(val)
}

func (m CmsUserM) RemarkGTEQ(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).GTEQ(val)
}

func (m CmsUserM) RemarkLike(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).Like(val)
}

func (m CmsUserM) RemarkNotLike(val string) sqlbuilder.Column {
	return ql.Col(m.Remark).NotLike(val)
}

func (m CmsUserM) RemarkDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Remark)
}

func (m CmsUserM) RemarkAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Remark)
}



func (m CmsUserM) UtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Utime).In(args...)
}

func (m CmsUserM) UtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Utime).NotIn(args...)
}

func (m CmsUserM) UtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).EQ(val)
}

func (m CmsUserM) UtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).NotEQ(val)
}

func (m CmsUserM) UtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).LT(val)
}

func (m CmsUserM) UtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).LTEQ(val)
}

func (m CmsUserM) UtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).GT(val)
}

func (m CmsUserM) UtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).GTEQ(val)
}

func (m CmsUserM) UtimeLike(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).Like(val)
}

func (m CmsUserM) UtimeNotLike(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Utime).NotLike(val)
}

func (m CmsUserM) UtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Utime)
}

func (m CmsUserM) UtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Utime)
}



func (m CmsUserM) CtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Ctime).In(args...)
}

func (m CmsUserM) CtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
    for _, val := range vals {
        args = append(args, val)
    }
    return ql.Col(m.Ctime).NotIn(args...)
}

func (m CmsUserM) CtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).EQ(val)
}

func (m CmsUserM) CtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).NotEQ(val)
}

func (m CmsUserM) CtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).LT(val)
}

func (m CmsUserM) CtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).LTEQ(val)
}

func (m CmsUserM) CtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).GT(val)
}

func (m CmsUserM) CtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).GTEQ(val)
}

func (m CmsUserM) CtimeLike(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).Like(val)
}

func (m CmsUserM) CtimeNotLike(val time.Time) sqlbuilder.Column {
	return ql.Col(m.Ctime).NotLike(val)
}

func (m CmsUserM) CtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(m.Ctime)
}

func (m CmsUserM) CtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(m.Ctime)
}
