// Code generated by "daox"; DO NOT EDIT.
package cmsnews

import (
	"github.com/fengjx/daox/v2/sqlbuilder"
	"github.com/fengjx/daox/v2/sqlbuilder/ql"

	"time"
)

const (
	TableName    = "cms_news"
	IDField      = "id"
	TitleField   = "title"
	ContentField = "content"
	TopicField   = "topic"
	StatusField  = "status"
	RemarkField  = "remark"
	UtimeField   = "utime"
	CtimeField   = "ctime"
)

var Meta = CmsnewsMeta{}

// CmsNewsM 新闻信息表
type CmsnewsMeta struct {
}

func (m CmsnewsMeta) TableName() string {
	return TableName
}

func (m CmsnewsMeta) IsAutoIncrement() bool {
	return true
}

func (m CmsnewsMeta) PrimaryKey() string {
	return "id"
}

func (m CmsnewsMeta) Columns() []string {
	return []string{
		"id",
		"title",
		"content",
		"topic",
		"status",
		"remark",
		"utime",
		"ctime",
	}
}

func IdIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).In(args...)
}

func IdNotIn(vals ...int64) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(IDField).NotIn(args...)
}

func IdEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).EQ(val)
}

func IdNotEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).NotEQ(val)
}

func IdLT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LT(val)
}

func IdLTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).LTEQ(val)
}

func IdGT(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GT(val)
}

func IdGTEQ(val int64) sqlbuilder.Column {
	return ql.Col(IDField).GTEQ(val)
}

func IdLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).Like(val)
}

func IdNotLike(val string) sqlbuilder.Column {
	return ql.Col(IDField).NotLike(val)
}

func IdDesc() sqlbuilder.OrderBy {
	return ql.Desc(IDField)
}

func IdAsc() sqlbuilder.OrderBy {
	return ql.Asc(IDField)
}

func TitleIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(TitleField).In(args...)
}

func TitleNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(TitleField).NotIn(args...)
}

func TitleEQ(val string) sqlbuilder.Column {
	return ql.Col(TitleField).EQ(val)
}

func TitleNotEQ(val string) sqlbuilder.Column {
	return ql.Col(TitleField).NotEQ(val)
}

func TitleLT(val string) sqlbuilder.Column {
	return ql.Col(TitleField).LT(val)
}

func TitleLTEQ(val string) sqlbuilder.Column {
	return ql.Col(TitleField).LTEQ(val)
}

func TitleGT(val string) sqlbuilder.Column {
	return ql.Col(TitleField).GT(val)
}

func TitleGTEQ(val string) sqlbuilder.Column {
	return ql.Col(TitleField).GTEQ(val)
}

func TitleLike(val string) sqlbuilder.Column {
	return ql.Col(TitleField).Like(val)
}

func TitleNotLike(val string) sqlbuilder.Column {
	return ql.Col(TitleField).NotLike(val)
}

func TitleDesc() sqlbuilder.OrderBy {
	return ql.Desc(TitleField)
}

func TitleAsc() sqlbuilder.OrderBy {
	return ql.Asc(TitleField)
}

func ContentIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ContentField).In(args...)
}

func ContentNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(ContentField).NotIn(args...)
}

func ContentEQ(val string) sqlbuilder.Column {
	return ql.Col(ContentField).EQ(val)
}

func ContentNotEQ(val string) sqlbuilder.Column {
	return ql.Col(ContentField).NotEQ(val)
}

func ContentLT(val string) sqlbuilder.Column {
	return ql.Col(ContentField).LT(val)
}

func ContentLTEQ(val string) sqlbuilder.Column {
	return ql.Col(ContentField).LTEQ(val)
}

func ContentGT(val string) sqlbuilder.Column {
	return ql.Col(ContentField).GT(val)
}

func ContentGTEQ(val string) sqlbuilder.Column {
	return ql.Col(ContentField).GTEQ(val)
}

func ContentLike(val string) sqlbuilder.Column {
	return ql.Col(ContentField).Like(val)
}

func ContentNotLike(val string) sqlbuilder.Column {
	return ql.Col(ContentField).NotLike(val)
}

func ContentDesc() sqlbuilder.OrderBy {
	return ql.Desc(ContentField)
}

func ContentAsc() sqlbuilder.OrderBy {
	return ql.Asc(ContentField)
}

func TopicIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(TopicField).In(args...)
}

func TopicNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(TopicField).NotIn(args...)
}

func TopicEQ(val string) sqlbuilder.Column {
	return ql.Col(TopicField).EQ(val)
}

func TopicNotEQ(val string) sqlbuilder.Column {
	return ql.Col(TopicField).NotEQ(val)
}

func TopicLT(val string) sqlbuilder.Column {
	return ql.Col(TopicField).LT(val)
}

func TopicLTEQ(val string) sqlbuilder.Column {
	return ql.Col(TopicField).LTEQ(val)
}

func TopicGT(val string) sqlbuilder.Column {
	return ql.Col(TopicField).GT(val)
}

func TopicGTEQ(val string) sqlbuilder.Column {
	return ql.Col(TopicField).GTEQ(val)
}

func TopicLike(val string) sqlbuilder.Column {
	return ql.Col(TopicField).Like(val)
}

func TopicNotLike(val string) sqlbuilder.Column {
	return ql.Col(TopicField).NotLike(val)
}

func TopicDesc() sqlbuilder.OrderBy {
	return ql.Desc(TopicField)
}

func TopicAsc() sqlbuilder.OrderBy {
	return ql.Asc(TopicField)
}

func StatusIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).In(args...)
}

func StatusNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(StatusField).NotIn(args...)
}

func StatusEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).EQ(val)
}

func StatusNotEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotEQ(val)
}

func StatusLT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LT(val)
}

func StatusLTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).LTEQ(val)
}

func StatusGT(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GT(val)
}

func StatusGTEQ(val string) sqlbuilder.Column {
	return ql.Col(StatusField).GTEQ(val)
}

func StatusLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).Like(val)
}

func StatusNotLike(val string) sqlbuilder.Column {
	return ql.Col(StatusField).NotLike(val)
}

func StatusDesc() sqlbuilder.OrderBy {
	return ql.Desc(StatusField)
}

func StatusAsc() sqlbuilder.OrderBy {
	return ql.Asc(StatusField)
}

func RemarkIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).In(args...)
}

func RemarkNotIn(vals ...string) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(RemarkField).NotIn(args...)
}

func RemarkEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).EQ(val)
}

func RemarkNotEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotEQ(val)
}

func RemarkLT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LT(val)
}

func RemarkLTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).LTEQ(val)
}

func RemarkGT(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GT(val)
}

func RemarkGTEQ(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).GTEQ(val)
}

func RemarkLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).Like(val)
}

func RemarkNotLike(val string) sqlbuilder.Column {
	return ql.Col(RemarkField).NotLike(val)
}

func RemarkDesc() sqlbuilder.OrderBy {
	return ql.Desc(RemarkField)
}

func RemarkAsc() sqlbuilder.OrderBy {
	return ql.Asc(RemarkField)
}

func UtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).In(args...)
}

func UtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(UtimeField).NotIn(args...)
}

func UtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).EQ(val)
}

func UtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).NotEQ(val)
}

func UtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LT(val)
}

func UtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).LTEQ(val)
}

func UtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GT(val)
}

func UtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(UtimeField).GTEQ(val)
}

func UtimeLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).Like(val)
}

func UtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(UtimeField).NotLike(val)
}

func UtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(UtimeField)
}

func UtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(UtimeField)
}

func CtimeIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).In(args...)
}

func CtimeNotIn(vals ...time.Time) sqlbuilder.Column {
	var args []any
	for _, val := range vals {
		args = append(args, val)
	}
	return ql.Col(CtimeField).NotIn(args...)
}

func CtimeEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).EQ(val)
}

func CtimeNotEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).NotEQ(val)
}

func CtimeLT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LT(val)
}

func CtimeLTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).LTEQ(val)
}

func CtimeGT(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GT(val)
}

func CtimeGTEQ(val time.Time) sqlbuilder.Column {
	return ql.Col(CtimeField).GTEQ(val)
}

func CtimeLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).Like(val)
}

func CtimeNotLike(val string) sqlbuilder.Column {
	return ql.Col(CtimeField).NotLike(val)
}

func CtimeDesc() sqlbuilder.OrderBy {
	return ql.Desc(CtimeField)
}

func CtimeAsc() sqlbuilder.OrderBy {
	return ql.Asc(CtimeField)
}
