// Code generated by "daox.gen"; DO NOT EDIT.
package entity


import (
	"time"
)


// SysMenu 系统菜单表
type SysMenu struct {
    ID int64 `json:"id"` // -
    ParentID int64 `json:"parent_id"` // 父级ID
    Name string `json:"name"` // 菜单名称
    Icon string `json:"icon"` // 图标
    Path string `json:"path"` // 菜单路径
    Redirect string `json:"redirect"` // 重定向地址
    SchemaAPI string `json:"schema_api"` // schema json url 地址
    SortNo int32 `json:"sort_no"` // 排序序号
    Visible int32 `json:"visible"` // 是否显示
    IsSys int32 `json:"is_sys"` // 是否是系统菜单
    Status string `json:"status"` // 状态
    Remark string `json:"remark"` // 备注
    Utime time.Time `json:"utime"` // 更新时间
    Ctime time.Time `json:"ctime"` // 创建时间
}

func (m *SysMenu) GetID() interface{} {
	return m.ID
}