// Code generated by "daox.gen"; DO NOT EDIT.
package entity


import (
	"time"
)


// SysDict 系统字典表
type SysDict struct {
    ID int64 `json:"id"` // -
    Group string `json:"group"` // 分组
    GroupName string `json:"group_name"` // 分组名称
    Value string `json:"value"` // 数据值
    Label string `json:"label"` // 显示标签
    Status string `json:"status"` // 数据状态
    Remark string `json:"remark"` // 备注
    Utime time.Time `json:"utime"` // 更新时间
    Ctime time.Time `json:"ctime"` // 创建时间
}

func (m *SysDict) GetID() interface{} {
	return m.ID
}