// Code generated by "daox.gen"; DO NOT EDIT.
package entity


import (
	"time"
)


// SysConfig 系统配置
type SysConfig struct {
    ID int64 `json:"id"` // -
    Scope string `json:"scope"` // 范围
    Key string `json:"key"` // 配置键
    Value string `json:"value"` // 配置值
    Status string `json:"status"` // 配置状态
    Remark string `json:"remark"` // 备注
    Utime time.Time `json:"utime"` // 更新时间
    Ctime time.Time `json:"ctime"` // 创建时间
}

func (m *SysConfig) GetID() interface{} {
	return m.ID
}